version: '3.7'

services:
  db:
    image: mysql:8.2.0
    volumes:
      - mysql_data:\MySQL\MySQL Server 8.0\Data\library_test
  web:
    build: .
    command:
      - python /app_dir/manage.py runserver 0.0.0.0.8000
      - python /app_dir/manage.py migrate
    volumes:
      - .:/app_dir
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  mysql_data: